application: bcmkejoules
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images
- url: /js
  static_dir: js
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: joules.py  