application: bcmke-joules
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /stylesheets
  static_dir: stylesheets

- url: /
  static_files: index.htm
  upload: index.htm

- url: /.*
  script: joules.py  
